add lifecycle hook to ASG on startup

diff --git a/foldingathome.yml b/foldingathome.yml
--- a/foldingathome.yml
+++ b/foldingathome.yml
@@ -106,10 +106,12 @@ Resources:
         - Key: Name
           Value: Folding@home
           PropagateAtLaunch: True
-    CreationPolicy:
-      ResourceSignal:
-        Count: !Ref InstanceCount
-        Timeout: 'PT10M' # 10 minutes
+      LifecycleHookSpecificationList:
+        - LifecycleTransition: "autoscaling:EC2_INSTANCE_LAUNCHING"
+          DefaultResult: ABANDON
+          HeartbeatTimeout: 600
+          LifecycleHookName: "InitialConfigurationHook"
+
 
   LaunchTemplate:
     Type: AWS::EC2::LaunchTemplate
@@ -139,6 +141,17 @@ Resources:
           Fn::Base64: !Sub |
             #!/bin/bash -ex
             exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
+            # error handling
+            function my_trap()
+            {
+              echo "Sorry, there was an error at line $1 $2" 
+              TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` 
+              aws autoscaling complete-lifecycle-action --lifecycle-action-result ABANDON --lifecycle-hook-name "InitialConfigurationHook" --auto-scaling-group-name !Ref AutoScalingGroup  \
+              --instance-id $(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-id) --region ${AWS::Region}
+              shutdown -h +60
+            }
+            trap 'my_trap $${LINENO} $$? ' ERR
+            # /error handling
             # Use instance store for Folding@home
             mkfs -t ext4 /dev/nvme0n1
             mkdir /var/lib/fahclient
@@ -180,7 +193,8 @@ Resources:
             cat<<END >/usr/local/bin/asg-unhealthy
             #!/bin/bash
             [ "\$SERVICE_RESULT" == "success" ] && exit 0
-            exec /usr/local/bin/aws autoscaling set-instance-health --instance-id $(curl http://169.254.169.254/latest/meta-data/instance-id) --health-status "Unhealthy" --region ${AWS::Region}
+            TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` 
+            exec /usr/local/bin/aws autoscaling set-instance-health --instance-id $(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-id) --health-status "Unhealthy" --region ${AWS::Region}
             END
             chmod a+rx /usr/local/bin/asg-unhealthy
             cat<<END >/etc/systemd/system/fahclient.service
@@ -200,7 +214,10 @@ Resources:
             systemctl enable fahclient
             systemctl start fahclient
             # send success signal
-            /usr/local/bin/cfn-signal --success true --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
+            TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` 
+            aws autoscaling complete-lifecycle-action --lifecycle-action-result CONTINUE --lifecycle-hook-name "InitialConfigurationHook" --auto-scaling-group-name !Ref AutoScalingGroup  \
+            --instance-id $(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-id) --region ${AWS::Region}
+  
 
   SecurityGroup:
     Type: AWS::EC2::SecurityGroup
